# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rhesus_factor',
            field=models.BooleanField(default=False),
        ),
    ]
