# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrest', '0003_auto_20180618_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_location',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
