# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrest', '0003_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.CharField(default='donor@gmail.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='donor',
            name='password',
            field=models.CharField(default='donor@gmail.com', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='first_time_donor',
            field=models.BooleanField(default=True),
        ),
    ]
